[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]
aptPkgs = ["gcc", "g++"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["python -c 'print(\"Build complete\")'"]

[start]
cmd = "uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"